package ui;

public enum Telas {
    MENU, CADASTRO_FORNECEDOR, CADASTRO_COMPRADOR, CADASTRO_TECNOLOGIA, CADASTRO_VENDA,
    RELATORIO_FORNECEDOR, RELATORIO_TECNOLOGIA,  RELATORIO_VENDA, RELATORIO_COMPRADOR,
    REMOVER_VENDA, ALTERAR_COMPRADOR, CONSULTA, SALVAR_DADOS, CARREGAR_DADOS
}
